// Build the Android debug APK via the Gradle wrapper generated by Capacitor.
// Requires the Android SDK (ANDROID_HOME / ANDROID_SDK_ROOT or ~/Android/Sdk) and a JDK.

import { existsSync } from "node:fs";
import { execSync } from "node:child_process";
import os from "node:os";
import path from "node:path";

const root = process.cwd();
const androidDir = path.join(root, "android");

if (!existsSync(androidDir)) {
  console.error("[build-apk] android/ project not found. Run `npx cap add android` first (after `npm run mobile:sync`).");
  process.exit(1);
}

// Resolve the Android SDK location.
const sdk =
  process.env.ANDROID_HOME ||
  process.env.ANDROID_SDK_ROOT ||
  (existsSync(path.join(os.homedir(), "Android", "Sdk")) ? path.join(os.homedir(), "Android", "Sdk") : "");

if (!sdk) {
  console.error("[build-apk] Android SDK not found. Set ANDROID_HOME or install the SDK at ~/Android/Sdk.");
  process.exit(1);
}

const gradlew = path.join(androidDir, process.platform === "win32" ? "gradlew.bat" : "gradlew");
console.log(`[build-apk] Using SDK: ${sdk}`);
try {
  execSync(`"${gradlew}" assembleDebug`, {
    cwd: androidDir,
    stdio: "inherit",
    env: { ...process.env, ANDROID_HOME: sdk, ANDROID_SDK_ROOT: sdk },
  });
} catch (error) {
  console.error("[build-apk] Gradle build failed:", error.message);
  process.exit(1);
}

const apk = path.join(androidDir, "app", "build", "outputs", "apk", "debug", "app-debug.apk");
console.log(existsSync(apk) ? `[build-apk] APK ready: ${apk}` : "[build-apk] Build finished but APK not found at the expected path.");
