name: Build and Release Desktop Apps

on:
  push:
    tags:
      - 'v*' # Se déclenche quand tu crées un tag (ex: v1.4.0)
  workflow_dispatch: # Permet de lancer la compilation manuellement depuis GitHub

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write # Permet à l'action de publier sur la page "Releases"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Prepare Web App
        run: npm run build

      - name: Prepare Desktop
        run: npm run desktop:prepare

      - name: Build and Publish Electron App
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --publish always
